/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

//#import "GrowlApplicationBridgeDelegate-Protocol.h"

@interface SPGrowlDelegate : NSObject //<GrowlApplicationBridgeDelegate>
{
}

+ (void)initialize;
+ (id)sharedInstance;
- (id)registrationDictionaryForGrowl;
- (void)notificationWithTrackInfo:(struct TrackInfo *)arg1;
- (void)growlNotificationWasClicked:(id)arg1;

@end

